name: Lint

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Run ShellCheck
        run: |
          git ls-files -z '*.sh' ':!:**/config.sh' \
            | xargs -0 shellcheck -x --source-path=SCRIPTDIR
