name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Create KoboRoot
        run: ./makeKoboRoot.sh

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create "$GITHUB_REF_NAME" KoboRoot.tgz --generate-notes
